version: "3.6"
services:
    chatgpt-webapi:
         image: chatgpt/chatgpt:latest
         build:
            context: .
            dockerfile: Dockerfile
         container_name: chatgpt-webapi
         environment:
            - OPENAI_USER=your@login.de
            - OPENAI_PASS=yourpass
         ports:
            - 8000:8000
         
         restart: unless-stopped
